---
version: "2.1"
services:
  prusaslicer-novnc:
    image: ghcr.io/eth4ck1e/prusaslicer-novnc:latest
    platform: linux/amd64
    build:
      context: .
      platforms:
        - linux/amd64
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - DISPLAY=:0
      - VGL_DISPLAY=egl
      - LIBVA_DRIVER_NAME=iHD
      - ENABLEHWGPU=true
      - VNC_RESOLUTION=1920x1080
    devices:
      - /dev/dri/:/dev/dri/
    volumes:
      - ./prints:/prints/
      - ./data:/configs/
    ports:
      - 8080:8080
    restart: unless-stopped
